ERROR 2015-08-31 17:58:52,788 13317ms BookTableController    Index              - First log from index class
INFO  2015-09-01 11:23:37,987 32154ms BookTableController    Index              - From action
INFO  2015-09-01 11:28:39,829 12288ms BookTableController    Index              - From action
ERROR 2015-09-01 11:59:20,706 37332ms BookTableController    Index              - Spesified restaurant Id is not valid.
ERROR 2015-09-01 11:59:26,298 42923ms BookTableController    Index              - Spesified restaurant Id is not valid.
ERROR 2015-09-01 17:28:59,576  7711ms RestaurantController   Index              - Cannot connect to the database.
ERROR 2015-09-02 15:29:30,089  8408ms RestaurantController   Index              - Cannot connect to the database. Exception: An error occurred while executing the command definition. See the inner exception for details.
ERROR 2015-09-02 16:06:14,423  5064ms RestaurantController   Index              - Cannot connect to the database. Exception: The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.
ERROR 2015-09-02 16:45:03,494  7615ms RestaurantController   Index              - Cannot connect to the database. Exception: An error occurred while executing the command definition. See the inner exception for details.
ERROR 2015-09-02 16:46:37,809  7643ms RestaurantController   Index              - Cannot connect to the database. Exception: An error occurred while executing the command definition. See the inner exception for details.
ERROR 2015-09-02 16:46:37,809  7643ms RestaurantController   Index              - Cannot connect to the database. Exception: An error occurred while executing the command definition. See the inner exception for details.
ERROR 2015-09-02 16:57:53,477  5298ms RestaurantController   Index              - Cannot connect to the database. Exception: Object reference not set to an instance of an object.
ERROR 2015-09-02 16:57:55,888  7710ms RestaurantController   Index              - Cannot connect to the database. Exception: An error occurred while executing the command definition. See the inner exception for details.
ERROR 2015-09-02 17:22:07,669  8032ms RestaurantController   Index              - Cannot connect to the database. Exception: An error occurred while executing the command definition. See the inner exception for details.
ERROR 2015-09-02 18:12:56,763  7838ms RestaurantController   Index              - Cannot connect to the database. Exception: Invalid attempt to call IsDBNull when reader is closed.
ERROR 2015-09-02 18:58:08,207  5342ms RestaurantController   Index              - The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
ERROR 2015-09-02 18:58:10,766  7902ms RestaurantController   Index              - An error occurred while executing the command definition. See the inner exception for details.   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
ERROR 2015-09-02 19:09:45,113  7597ms RestaurantController   Index              - An error occurred while executing the command definition. See the inner exception for details.   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
ERROR 2015-09-03 10:44:15,208  7717ms RestaurantController   Index              - Invalid attempt to call IsDBNull when reader is closed.   at System.Data.SqlClient.SqlDataReader.CheckHeaderIsReady(Int32 columnIndex, Boolean permitAsync, String methodName)
   at System.Data.SqlClient.SqlDataReader.IsDBNull(Int32 i)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
ERROR 2015-09-03 10:57:26,219  5275ms RestaurantController   Index              - Object reference not set to an instance of an object.   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
ERROR 2015-09-03 10:58:02,881  4928ms RestaurantController   Index              - The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
ERROR 2015-09-03 11:00:14,442 17610ms RestaurantController   Index              - The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
ERROR 2015-09-03 12:55:09,203  5015ms RestaurantController   Index              - The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OdeToFood.Data.Repository`1.GetAll() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood.Data\Repository.cs:line 23
   at OdeToFood.Controllers.RestaurantController.Index() in c:\Users\vbesedina\Desktop\OdeToFood\OdeToFood\Controllers\RestaurantController.cs:line 33
